import sqlite3

conn = sqlite3.connect("Proj.db")

c = conn.cursor()

#c.execute('''CREATE TABLE CHEF (CHEF_ID INT, CHEF_LNAME VARCHAR(45), CHEF_FNAME VARCHAR(45))''')

#c.execute('''CREATE TABLE INGREDIENT (INGREDIENT_NUM INT, INGREDIENT_NAME VARCHAR(45), INGREDIENT_UNIT VARCHAR(45), INGREDIENT_UNIT_PRICE VARCHAR(45)) ''')

#c.execute('''CREATE TABLE RECIPE (QNTY FLOAT, INGREDIENT_NUM INT, MEAL_ID INT)''')

#c.execute('''CREATE TABLE  MAKES (CHEF_ID INT, MEAL_ID INT)''')

#c.execute('''CREATE TABLE MEAL (MEAL_ID INT, MEAL_NAME VARCHAR(45))''')

c.close()