# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerView.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 631, 611))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMyRecipes = QtWidgets.QWidget()
        self.tabMyRecipes.setObjectName("tabMyRecipes")
        self.recipeList = QtWidgets.QListWidget(self.tabMyRecipes)
        self.recipeList.setGeometry(QtCore.QRect(20, 40, 251, 541))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(11)
        self.recipeList.setFont(font)
        self.recipeList.setObjectName("recipeList")
        self.listWidget = QtWidgets.QListWidget(self.tabMyRecipes)
        self.listWidget.setGeometry(QtCore.QRect(280, 40, 341, 531))
        self.listWidget.setObjectName("listWidget")
        self.btnRemoveChef = QtWidgets.QPushButton(self.tabMyRecipes)
        self.btnRemoveChef.setGeometry(QtCore.QRect(420, 0, 198, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        self.btnRemoveChef.setFont(font)
        self.btnRemoveChef.setObjectName("btnRemoveChef")
        self.pushButton_4 = QtWidgets.QPushButton(self.tabMyRecipes)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 141, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tabMyRecipes, "")
        self.tabAllRecipes = QtWidgets.QWidget()
        self.tabAllRecipes.setObjectName("tabAllRecipes")
        self.recipeList_2 = QtWidgets.QListWidget(self.tabAllRecipes)
        self.recipeList_2.setGeometry(QtCore.QRect(10, 40, 251, 531))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(11)
        self.recipeList_2.setFont(font)
        self.recipeList_2.setObjectName("recipeList_2")
        self.btnRemoveRecipe = QtWidgets.QPushButton(self.tabAllRecipes)
        self.btnRemoveRecipe.setGeometry(QtCore.QRect(430, 0, 198, 33))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        self.btnRemoveRecipe.setFont(font)
        self.btnRemoveRecipe.setObjectName("btnRemoveRecipe")
        self.label_8 = QtWidgets.QLabel(self.tabAllRecipes)
        self.label_8.setGeometry(QtCore.QRect(270, 10, 71, 21))
        self.label_8.setObjectName("label_8")
        self.PriceLabel = QtWidgets.QLabel(self.tabAllRecipes)
        self.PriceLabel.setGeometry(QtCore.QRect(330, 10, 91, 21))
        self.PriceLabel.setText("")
        self.PriceLabel.setObjectName("PriceLabel")
        self.listWidget_2 = QtWidgets.QListWidget(self.tabAllRecipes)
        self.listWidget_2.setGeometry(QtCore.QRect(270, 40, 351, 531))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tabAllRecipes)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 141, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tabAllRecipes, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 30, 200, 630))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ingredientOne = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ingredientOne.setObjectName("ingredientOne")
        self.verticalLayout.addWidget(self.ingredientOne)
        self.btnSearch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(10)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout.addWidget(self.btnSearch)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnRemoveChef.setText(_translate("MainWindow", "Remove Chef"))
        self.pushButton_4.setText(_translate("MainWindow", "Update List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMyRecipes), _translate("MainWindow", "Chefs"))
        self.btnRemoveRecipe.setText(_translate("MainWindow", "Remove Recipe"))
        self.label_8.setText(_translate("MainWindow", "Price:"))
        self.pushButton_3.setText(_translate("MainWindow", "Update List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAllRecipes), _translate("MainWindow", "All Recipes"))
        self.btnAdd.setText(_translate("MainWindow", "Add Recipe"))
        self.label.setText(_translate("MainWindow", "Find me recipes with:"))
        self.label_2.setText(_translate("MainWindow", "Ingredient:"))
        self.btnSearch.setText(_translate("MainWindow", "Search"))
        self.pushButton.setText(_translate("MainWindow", "Add Chef"))
        self.label_5.setText(_translate("MainWindow", "Search a Chef"))
        self.label_6.setText(_translate("MainWindow", "First Name:"))
        self.label_7.setText(_translate("MainWindow", "Last Name:"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))


